### ISSUE TITLE
友链添加请求

### ISSUE THREAD

**Issue by C9QuaRtz** [MaStAr1128/mastar1128.github.io#1]
**MaStAr1128** 大佬，我想在我的个人博客添加指向你博客的友链，可以吗？
你的友链会发在 [这里](https://c9quartz.github.io/links/ "乐子神在上 你知道这会去哪里的吧（")，感兴趣的话请来看看吧。

如果可以的话，你也能添加一个友链页吗？这应该不会很难。

**Comment by MaStAr1128** [comment]
@C9QuaRtz 当然可以，我会在 2024-12-01T00:00:00+08:00 前完成相关更新。

**Comment by MaStAr1128** [comment]
丐中丐版友链功能已上线。
